### PR TITLE
added listings route with only index, new, create

### PR DESCRIPTION
**Pull request by KarasuGummi**
resources :listings, only: %i[index new create]

### CODE REVIEW

**Comment by KevinMCollier** [comment]
What about the destroy route?

**Comment by KarasuGummi** [comment]
omg how could i forget

**Comment by KevinMCollier** [comment]
it's okay, it happens to us all

**Comment by KarasuGummi** [comment]
i hope this makes you happy

**Review by KevinMCollier — COMMENTED** [review]
Looks fantastics!

**Review by KarasuGummi — COMMENTED** [review]
testing the merge

**Pull request merged**
